Capstone project for module one
yasinabdmahmood/Capstone-Project pull request #1
Opened 2022-08-02 21:03 UTC by yasinabdmahmood

### Project implementation

- The content has been personalized and is different from the original design.
-  This [design guidelines](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015) is used including:
  - Colors.
  - Typography: font face, size, and weight ( [Lato](https://www.latofonts.com/) is used as it is a free font similar to the one used in the original design).
  - Layout: composition and space between elements are designed to match the original design as much as possible.
- The page looks almost identical to the original design. Small adjustments like text or image changes are implemented.

- Only these 2 pages have been built:
  - The *home page*.
  - The *about page*.
- Each of these pages has two versions for 2 different screen sizes: 
  - Mobile: up to 768px wide.
  - Desktop: 768px or wider.

- Interactions
  - Links
    - The *home page* hasa link in the menu to the *about page*.
    - The logo in the header links to the *home page*.
  - Mobile menu
    - When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
    - The mobile menu has a close (X) button that closes the menu.
- Dynamic page
  - The section "Featured speakers" is created dynamically in JavaScript.
  -  JavaScript variable has been used with the data about the speakers and used when the page loads to create the HTML for this section dynamically.

2022-08-02 22:55 UTC, tufoinnkuo10 requested changes
Hi @yasinabdmahmood 

Great job so far. There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally
✅ Mobile menu hamburger works as expected
✅ design well followed

## Required Changes ♻️
Check the comments under the review

![tufoin](https://media.giphy.com/media/a6O5pzQ8pAPTCoeagK/giphy.gif)

Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-08-02 22:55 UTC, tufoinnkuo10 commented on README.md
> +> In this website you will learn how to create a web application using the Html Css and Javascript.
- [ ] kindly add a good description of what your project is all about.  From the README the user will know what to expect

2022-08-02 22:55 UTC, tufoinnkuo10 commented on about.html
> +                        <a href="#">Program</a>
- [ optional] you can add links to different page sections so as to ease navigation

2022-08-02 22:55 UTC, tufoinnkuo10 commented on index.html
> +            <button class="btn1">
- [ ] great job with the mobile menu. Please kindly ensure that it covers the whole page when it pops-up.
![Screenshot (278)_LI](https://user-images.githubusercontent.com/65298048/182483144-b0cf4369-ae5e-42ae-ac8e-f452b7d25444.jpg)

2022-08-02 22:55 UTC, tufoinnkuo10 commented on index.html
> +            <h1 class="main-topic-text" >SCIENCE AND
- [ ] kindly make the h1 heading bolder or add the font weight so it looks like the Behance design

2022-08-02 22:55 UTC, tufoinnkuo10 commented on main.js
> +    img: './img/speaker_01.png',
- [ ] add a little bit of margin to the images so the realy follow the behance design.. great work
your design 👇🏾 
![Screenshot (280)_LI](https://user-images.githubusercontent.com/65298048/182485847-78b34130-38ca-437c-acb8-194068e2ccdb.jpg)
behance design 👇🏾 
![Screenshot (281)_LI](https://user-images.githubusercontent.com/65298048/182485934-4f9de4ac-4b24-4998-955a-eb2c7c4a6edc.jpg)

2022-08-03 05:30 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)
Hey @yasinabdmahmood  :wave:

Great work on implementing the requirements. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:
:heavy_check_mark: Followed Linters
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary

### [Optional]

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 05:32 UTC, merged